# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STR', 'Strategy'), ('ACT', 'Action'), ('PLT', 'Platformer'), ('SHT', 'Shooter'), ('ADV', 'Adventure'), ('RPG', 'Role-playing game'), ('SND', 'Sandbox'), ('FNT', 'Fantasy'), ('MLT', 'Multiplayer'), ('TDF', 'Tower defence'), ('TRN', 'Turn based'), ('RLT', 'Real time'), ('ONL', 'Online'), ('SPR', 'Sports'), ('UND', 'Undefined')], default='UND', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='www.google.com')),
                ('sold', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(to='webgamestore.Category')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='webgamestore.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Gamestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='{}', max_length=512)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestates', to='webgamestore.Game')),
            ],
            options={
                'ordering': ['dateTime'],
            },
        ),
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to='webgamestore.Game')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPerDay', to='webgamestore.Game')),
            ],
        ),
        migrations.AddField(
            model_name='highscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to='webgamestore.Player'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestates', to='webgamestore.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='webgamestore.Player'),
        ),
    ]
